package app.ui

/** Bilingual string table for the desktop app. Switch via [Strings.lang]. */
object Strings {
    enum class Lang { NL, EN }

    var lang: Lang = Lang.NL

    private val tables: Map<Lang, Map<String, String>> = mapOf(
        Lang.NL to mapOf(
            "appTitle" to "1828 · Fasedocument Tracker",
            // Login / signup
            "loginTitle" to "Inloggen",
            "loginSub" to "Log in met je 1828-account.",
            "labelEmail" to "E-mailadres",
            "labelPassword" to "Wachtwoord",
            "labelName" to "Naam",
            "btnLogin" to "Inloggen →",
            "noAccount" to "Nog geen account?",
            "createAccount" to "Account aanvragen",
            "haveAccount" to "Heb je al een account?",
            "backToLogin" to "Terug naar inloggen",
            "signupTitle" to "Account aanvragen",
            "signupSub" to "Vul je gegevens in. Een eigenaar van 1828 keurt je account goed.",
            "labelRequestedRole" to "Gewenste rol",
            "btnSignup" to "Aanvragen",
            "signupSubmitted" to "Aanvraag ingediend",
            "signupSubmittedDesc" to "Je account wacht op goedkeuring van de eigenaar.",
            "loginFailUnknown" to "E-mailadres niet bekend.",
            "loginFailPassword" to "Wachtwoord onjuist.",
            "loginFailPending" to "Account wacht op goedkeuring.",
            "loginFailRejected" to "Aanvraag is afgewezen.",
            "signupFailEmail" to "Ongeldig e-mailadres.",
            "signupFailWeak" to "Wachtwoord te kort (min. 4 tekens).",
            "signupFailExists" to "Account bestaat al.",
            "demoHint" to "Demo: ernest@1828.nl / ernest",
            "btnLogout" to "Uitloggen",
            "btnDashboard" to "🏠 Dashboard",
            "btnApprovals" to "📥 Goedkeuringen",
            "btnUserAdmin" to "👥 Gebruikers",
            "labelRole" to "Jouw rol",
            "roleAll" to "Alle rollen (projectlead)",
            "roleOM" to "Ontwikkelmanager (OM)",
            "rolePO" to "Projectontwikkelaar (PO)",
            "rolePM" to "Projectmanager (PM)",
            "rolePPM" to "Property Manager (PPM)",
            "roleMT" to "Management Team (MT) — goedkeurder",
            "btnStart" to "Start →",
            "btnAdmin" to "⚙ Admin-modus",
            "adminNote" to "⚠ Admin-modus aan: blokken/taken kunnen worden herschikt en eigen rijen toegevoegd.",
            "cities" to "Steden",
            "projects" to "Projecten",
            "addCity" to "+ Stad",
            "addProject" to "+ Project",
            "noCities" to "Nog geen steden. Klik \"+ Stad\" om er een toe te voegen.",
            "noProjects" to "Nog geen projecten. Klik \"+ Project\" om er een toe te voegen.",
            "welcomeTitle" to "Kies waar je aan wilt werken",
            "welcomeSub" to "Steden volgen Gemeenteontwikkeling per stad (doorlopend). Projecten volgen het fase-voor-fase proces met goedkeuring.",
            "pickCity" to "Stad",
            "pickCityDesc" to "Doorlopend traject Gemeenteontwikkeling per gemeente.",
            "pickProject" to "Project",
            "pickProjectDesc" to "Acquisitie → Garantie, met formele fase-goedkeuring.",
            "btnBack" to "← Terug",
            "btnAdminOff" to "Admin uit",
            "btnAdminOn" to "⚙ Admin",
            "filterLabel" to "Filter:",
            "filterAll" to "Alle",
            "btnMarkAll" to "Alles ✓",
            "btnUnmarkAll" to "Alles ✗",
            "addRow" to "+ Regel toevoegen",
            "addRowPrompt" to "Naam van de nieuwe deliverable:",
            "deleteRowConfirm" to "Eigen regel verwijderen?",
            "namePromptCity" to "Naam van de gemeente (bijv. Leiden, Amsterdam):",
            "namePromptProject" to "Naam van het project (bijv. Utrecht Oost):",
            "duplicateName" to "Deze naam bestaat al.",
            "customTag" to "eigen",
            "naLabel" to "N.v.t.",
            "submitForApproval" to "Indienen ter goedkeuring",
            "submittedTitle" to "Ingediend ter goedkeuring",
            "submittedDesc" to "Wachten op goedkeuring van de goedkeurder. Volgende fase blijft vergrendeld.",
            "withdraw" to "Intrekken",
            "approvePhase" to "✓ Fase goedkeuren",
            "rejectPhase" to "✗ Afwijzen",
            "approvedTitle" to "Fase goedgekeurd",
            "approvedDesc" to "Volgende fase is ontgrendeld.",
            "reopenPhase" to "Heropen fase",
            "readyTitle" to "Alle taken zijn afgerond of als n.v.t. gemarkeerd.",
            "readyDesc" to "Klik op \"Indienen ter goedkeuring\" om deze fase af te ronden.",
            "needsApprover" to "Alleen MT (goedkeurder) of admin kan een fase goedkeuren.",
            "lockedTitle" to "Deze fase is vergrendeld.",
            "lockedSub" to "Eerst moet de vorige fase worden goedgekeurd.",
            "crumbCities" to "Steden",
            "crumbProjects" to "Projecten",
            "statDone" to "Klaar",
            "statNa" to "N.v.t.",
            "statOpen" to "Open",
            "statLink" to "Met document",
            "exportTitle" to "Exporteer naar fasedocument",
            "exportDesc" to "Exporteer alle steden en projecten naar Excel.",
            "exportBtn" to "⬇ Exporteer Excel",
            "adminBadge" to "Admin",
            "fase" to "Fase",
            "fasen" to "fasen",
            "of" to "van",
            "tasks" to "taken",
            "applicable" to "van toepassing",
            "approver" to "Goedkeurder",
            "linkPlaceholder" to "Link of locatie document…",
            "cityNotFound" to "Stad niet gevonden",
            "projectNotFound" to "Project niet gevonden",
            "exportSuccess" to "Export geschreven:",
            "exportFailed" to "Export mislukt:",
            // Dashboard / city detail
            "dashboardTitle" to "Dashboard",
            "dashboardSub" to "Steden van 1828. Klik een stad om de projecten te bekijken.",
            "projectsInCity" to "Projecten in",
            "noProjectsInCity" to "Nog geen projecten in deze stad. Voeg er een toe.",
            "projectCount" to "projecten",
            "projectCountOne" to "project",
            "phaseLabel" to "fase",
            "pickCityForProject" to "Onder welke stad valt dit project?",
            "noAccessibleCities" to "Je hebt nog geen toegang tot steden. Vraag de eigenaar om toegang.",
            // Approvals inbox / user admin
            "approvalsTitle" to "Goedkeuringen",
            "approvalsSub" to "Openstaande verzoeken voor de eigenaar.",
            "phaseSubmissions" to "Fase-goedkeuringen",
            "noPhaseSubmissions" to "Geen openstaande fases.",
            "pendingSignups" to "Account-aanvragen",
            "noPendingSignups" to "Geen openstaande aanvragen.",
            "btnApprove" to "Goedkeuren",
            "btnReject" to "Afwijzen",
            "openProject" to "Open project",
            "userAdminTitle" to "Gebruikersbeheer",
            "userAdminSub" to "Beheer rollen en toegang per gebruiker.",
            "colName" to "Naam",
            "colEmail" to "E-mail",
            "colRole" to "Rol",
            "colStatus" to "Status",
            "colAccess" to "Toegang",
            "statusActive" to "Actief",
            "statusPending" to "In afwachting",
            "statusRejected" to "Afgewezen",
            "accessAll" to "Alles",
            "managerAccessHint" to "Klik op de stadsknoppen om toegang te wisselen.",
            "pendingBadge" to "open",
            "loggedInAs" to "Ingelogd als",
            // Outbox / notifications
            "btnOutbox" to "✉ Meldingen",
            "outboxTitle" to "E-mailmeldingen",
            "outboxSub" to "Automatisch verzonden e-mails. Zonder SMTP-configuratie blijven ze hier zichtbaar en worden ze als .eml-bestand opgeslagen.",
            "outboxEmpty" to "Nog geen meldingen.",
            "openOutboxFolder" to "📂 Open e-mailmap",
            "toLabel" to "Aan",
            "fromLabel" to "Van",
            "viaLabel" to "via",
            "evSubmitted" to "Deliverable afgerond",
            "evApprovalRequested" to "Goedkeuring gevraagd",
            "evApproved" to "Fase goedgekeurd",
            "evRejected" to "Fase afgewezen",
            // Dashboard v2
            "statOpenTasks" to "Open taken",
            "statPendingApprovals" to "Wacht op goedkeuring",
            "dashApprovalsHeading" to "⏳ Wacht op jouw goedkeuring",
            "dashActivityHeading" to "✉ Recente meldingen",
            "viewAll" to "Bekijk alles →",
            // Email templates
            "subjSubmitted1" to "✅ Deliverable afgerond: {task}",
            "subjSubmittedN" to "✅ {n} deliverables afgerond — {ctx}",
            "subjApproval" to "📥 Goedkeuring gevraagd: {project} — {phase}",
            "subjApproved" to "🎉 Fase goedgekeurd: {project} — {phase}",
            "subjRejected" to "↩ Fase afgewezen: {project} — {phase}",
            "mailSubmittedIntro1" to "Er is een deliverable afgerond.",
            "mailSubmittedIntroN" to "Er zijn {n} deliverables afgerond.",
            "mailApprovalIntro" to "{user} vraagt goedkeuring voor een fase.",
            "mailApprovedIntro" to "{user} heeft de fase goedgekeurd.",
            "mailRejectedIntro" to "{user} heeft de fase afgewezen. Controleer de taken en dien opnieuw in.",
            "mailNextPhase" to "Volgende fase ontgrendeld: {phase}",
            "mailLastPhase" to "Dit was de laatste fase van het project. 🎉",
            "mailAction" to "Actie: open de 1828 Tracker → Goedkeuringen om te beoordelen.",
            "mailBy" to "Door",
            "mailWhen" to "Tijdstip",
            "lblContext" to "Betreft",
            "lblProject" to "Project",
            "lblPhase" to "Fase",
            // Google Drive attachments
            "addDocument" to "+ 📎 Document",
            "attachDialogTitle" to "Document koppelen",
            "attachUrlLabel" to "Google Drive-link of URL",
            "attachNameLabel" to "Naam (optioneel)",
            "attachInvalidUrl" to "Ongeldige link.",
            "reviewDocs" to "Documenten voor review",
            "mailDocs" to "Documenten",
            "kindFolder" to "Drive-map",
            "kindFile" to "Drive-bestand",
            "kindLink" to "Link",
            // Password reset / change
            "forgotPassword" to "Wachtwoord vergeten?",
            "resetTitle" to "Wachtwoord opnieuw instellen",
            "resetSub" to "Vul je e-mailadres in; je ontvangt een code per e-mail.",
            "btnSendCode" to "Stuur code",
            "resetCodeSent" to "Code verzonden. Bekijk je e-mail (in deze demo: de outbox-map).",
            "labelCode" to "Code uit de e-mail",
            "labelNewPassword" to "Nieuw wachtwoord",
            "labelConfirmPassword" to "Bevestig wachtwoord",
            "btnResetPassword" to "Stel wachtwoord in",
            "resetSuccess" to "Wachtwoord bijgewerkt. Log in met je nieuwe wachtwoord.",
            "resetFailBadCode" to "Code onjuist of verlopen.",
            "pwMismatch" to "Wachtwoorden komen niet overeen.",
            "changePwTitle" to "Wachtwoord wijzigen",
            "labelCurrentPassword" to "Huidig wachtwoord",
            "changePwSuccess" to "Wachtwoord gewijzigd.",
            "changePwFailCurrent" to "Huidig wachtwoord onjuist.",
            "subjReset" to "🔑 Code voor wachtwoord-reset",
            "mailResetIntro" to "Gebruik deze code om je wachtwoord opnieuw in te stellen:",
            "mailResetIgnore" to "Geen reset aangevraagd? Negeer deze e-mail.",
            "evReset" to "Wachtwoord-reset",
            // Remove user
            "btnRemoveUser" to "Verwijderen",
            "removeUserTitle" to "Gebruiker verwijderen",
            "removeUserPrompt" to "Kies wie de documenten en verantwoordelijkheden van {user} overneemt:",
            "removeUserConfirmBtn" to "Verwijder en draag over",
            "removedInfo" to "{user} verwijderd. {n} document(en) overgedragen aan {to}.",
            "cannotRemoveOwner" to "De eigenaar kan niet worden verwijderd.",
            // Unfinished tasks on submit
            "notReadyBanner" to "Nog {n} taken open in deze fase.",
            "btnProceed" to "Ga verder",
            "unfinishedPrompt" to "Er zijn nog onafgeronde taken ({n}) — wil je toch indienen ter goedkeuring?",
            "unfinishedChoice" to "Wat moet er gebeuren met de {n} open taken?",
            "optMarkNa" to "Markeer als n.v.t.",
            "optMoveNext" to "Verplaats naar volgende fase (WIP)",
            // City gate (Gemeenteontwikkeling vóór Acquisitiefase)
            "lblCity" to "Stad",
            "cityApprovedTitle" to "Gemeenteontwikkeling goedgekeurd",
            "cityApprovedDesc" to "Projecten in deze stad zijn ontgrendeld.",
            "cityLockedMsg" to "Eerst moet Gemeenteontwikkeling van {city} zijn goedgekeurd.",
            "cityGateHint" to "Projecten ontgrendelen zodra Gemeenteontwikkeling is goedgekeurd.",
            "subjCityApproval" to "📥 Goedkeuring gevraagd: Gemeenteontwikkeling — {city}",
            "subjCityApproved" to "🎉 Gemeenteontwikkeling goedgekeurd — {city}",
            "subjCityRejected" to "↩ Indiening afgewezen: Gemeenteontwikkeling — {city}",
            "mailCityApprovalIntro" to "{user} vraagt goedkeuring voor Gemeenteontwikkeling.",
            "mailCityApprovedIntro" to "{user} heeft Gemeenteontwikkeling goedgekeurd. Projecten in de stad zijn ontgrendeld.",
            "mailCityRejectedIntro" to "{user} heeft de indiening afgewezen. Controleer de taken en dien opnieuw in.",
            // Zoom
            "zoomTooltip" to "Tekstgrootte — klik op het percentage om te herstellen",
        ),
        Lang.EN to mapOf(
            "appTitle" to "1828 · Phase Document Tracker",
            // Login / signup
            "loginTitle" to "Sign in",
            "loginSub" to "Sign in with your 1828 account.",
            "labelEmail" to "Email",
            "labelPassword" to "Password",
            "labelName" to "Name",
            "btnLogin" to "Sign in →",
            "noAccount" to "No account yet?",
            "createAccount" to "Request an account",
            "haveAccount" to "Already have an account?",
            "backToLogin" to "Back to sign-in",
            "signupTitle" to "Request an account",
            "signupSub" to "Fill in your details. An 1828 owner will review and approve.",
            "labelRequestedRole" to "Requested role",
            "btnSignup" to "Submit request",
            "signupSubmitted" to "Request submitted",
            "signupSubmittedDesc" to "Your account is awaiting approval from the owner.",
            "loginFailUnknown" to "Email not recognised.",
            "loginFailPassword" to "Wrong password.",
            "loginFailPending" to "Account awaiting approval.",
            "loginFailRejected" to "Account request was rejected.",
            "signupFailEmail" to "Invalid email.",
            "signupFailWeak" to "Password too short (min. 4 characters).",
            "signupFailExists" to "An account with this email already exists.",
            "demoHint" to "Demo: ernest@1828.nl / ernest",
            "btnLogout" to "Sign out",
            "btnDashboard" to "🏠 Dashboard",
            "btnApprovals" to "📥 Approvals",
            "btnUserAdmin" to "👥 Users",
            "labelRole" to "Your role",
            "roleAll" to "All roles (project lead)",
            "roleOM" to "Development Manager (OM)",
            "rolePO" to "Project Developer (PO)",
            "rolePM" to "Project Manager (PM)",
            "rolePPM" to "Property Manager (PPM)",
            "roleMT" to "Management Team (MT) — approver",
            "btnStart" to "Start →",
            "btnAdmin" to "⚙ Admin mode",
            "adminNote" to "⚠ Admin mode on: bloks/tasks can be reordered and custom rows added.",
            "cities" to "Cities",
            "projects" to "Projects",
            "addCity" to "+ City",
            "addProject" to "+ Project",
            "noCities" to "No cities yet. Click \"+ City\" to add one.",
            "noProjects" to "No projects yet. Click \"+ Project\" to add one.",
            "welcomeTitle" to "Pick what to work on",
            "welcomeSub" to "Cities track ongoing Municipality Development per city. Projects follow the phase-by-phase flow with formal approval.",
            "pickCity" to "City",
            "pickCityDesc" to "Ongoing Municipality Development per city.",
            "pickProject" to "Project",
            "pickProjectDesc" to "Acquisition → Warranty, with formal phase approval.",
            "btnBack" to "← Back",
            "btnAdminOff" to "Admin off",
            "btnAdminOn" to "⚙ Admin",
            "filterLabel" to "Filter:",
            "filterAll" to "All",
            "btnMarkAll" to "All ✓",
            "btnUnmarkAll" to "All ✗",
            "addRow" to "+ Add row",
            "addRowPrompt" to "Name of the new deliverable:",
            "deleteRowConfirm" to "Delete custom row?",
            "namePromptCity" to "City name (e.g. Leiden, Amsterdam):",
            "namePromptProject" to "Project name (e.g. Utrecht East):",
            "duplicateName" to "That name already exists.",
            "customTag" to "custom",
            "naLabel" to "N/A",
            "submitForApproval" to "Submit for approval",
            "submittedTitle" to "Submitted for approval",
            "submittedDesc" to "Awaiting approval. The next phase stays locked until then.",
            "withdraw" to "Withdraw",
            "approvePhase" to "✓ Approve phase",
            "rejectPhase" to "✗ Reject",
            "approvedTitle" to "Phase approved",
            "approvedDesc" to "The next phase is now unlocked.",
            "reopenPhase" to "Reopen phase",
            "readyTitle" to "All tasks are done or marked N/A.",
            "readyDesc" to "Click \"Submit for approval\" to complete this phase.",
            "needsApprover" to "Only MT (approver) or admin can approve a phase.",
            "lockedTitle" to "This phase is locked.",
            "lockedSub" to "The previous phase must be approved first.",
            "crumbCities" to "Cities",
            "crumbProjects" to "Projects",
            "statDone" to "Done",
            "statNa" to "N/A",
            "statOpen" to "Open",
            "statLink" to "With document",
            "exportTitle" to "Export to phase document",
            "exportDesc" to "Export all cities and projects to Excel.",
            "exportBtn" to "⬇ Export Excel",
            "adminBadge" to "Admin",
            "fase" to "Phase",
            "fasen" to "phases",
            "of" to "of",
            "tasks" to "tasks",
            "applicable" to "applicable",
            "approver" to "Approver",
            "linkPlaceholder" to "Link or document location…",
            "cityNotFound" to "City not found",
            "projectNotFound" to "Project not found",
            "exportSuccess" to "Export written:",
            "exportFailed" to "Export failed:",
            // Dashboard / city detail
            "dashboardTitle" to "Dashboard",
            "dashboardSub" to "1828 cities. Click a city to see its projects.",
            "projectsInCity" to "Projects in",
            "noProjectsInCity" to "No projects in this city yet. Add one.",
            "projectCount" to "projects",
            "projectCountOne" to "project",
            "phaseLabel" to "phase",
            "pickCityForProject" to "Which city does this project belong to?",
            "noAccessibleCities" to "You don't have access to any cities yet. Ask the owner for access.",
            // Approvals inbox / user admin
            "approvalsTitle" to "Approvals",
            "approvalsSub" to "Open requests waiting for the owner.",
            "phaseSubmissions" to "Phase approvals",
            "noPhaseSubmissions" to "No open phase submissions.",
            "pendingSignups" to "Account requests",
            "noPendingSignups" to "No open signup requests.",
            "btnApprove" to "Approve",
            "btnReject" to "Reject",
            "openProject" to "Open project",
            "userAdminTitle" to "User management",
            "userAdminSub" to "Manage roles and access per user.",
            "colName" to "Name",
            "colEmail" to "Email",
            "colRole" to "Role",
            "colStatus" to "Status",
            "colAccess" to "Access",
            "statusActive" to "Active",
            "statusPending" to "Pending",
            "statusRejected" to "Rejected",
            "accessAll" to "All",
            "managerAccessHint" to "Click the city chips to toggle access.",
            "pendingBadge" to "open",
            "loggedInAs" to "Signed in as",
            // Outbox / notifications
            "btnOutbox" to "✉ Notifications",
            "outboxTitle" to "Email notifications",
            "outboxSub" to "Automatically sent emails. Without SMTP configuration they stay visible here and are saved as .eml files.",
            "outboxEmpty" to "No notifications yet.",
            "openOutboxFolder" to "📂 Open email folder",
            "toLabel" to "To",
            "fromLabel" to "From",
            "viaLabel" to "via",
            "evSubmitted" to "Deliverable completed",
            "evApprovalRequested" to "Approval requested",
            "evApproved" to "Phase approved",
            "evRejected" to "Phase rejected",
            // Dashboard v2
            "statOpenTasks" to "Open tasks",
            "statPendingApprovals" to "Awaiting approval",
            "dashApprovalsHeading" to "⏳ Awaiting your approval",
            "dashActivityHeading" to "✉ Recent notifications",
            "viewAll" to "View all →",
            // Email templates
            "subjSubmitted1" to "✅ Deliverable completed: {task}",
            "subjSubmittedN" to "✅ {n} deliverables completed — {ctx}",
            "subjApproval" to "📥 Approval requested: {project} — {phase}",
            "subjApproved" to "🎉 Phase approved: {project} — {phase}",
            "subjRejected" to "↩ Phase rejected: {project} — {phase}",
            "mailSubmittedIntro1" to "A deliverable has been completed.",
            "mailSubmittedIntroN" to "{n} deliverables have been completed.",
            "mailApprovalIntro" to "{user} requests approval for a phase.",
            "mailApprovedIntro" to "{user} approved the phase.",
            "mailRejectedIntro" to "{user} rejected the phase. Review the tasks and resubmit.",
            "mailNextPhase" to "Next phase unlocked: {phase}",
            "mailLastPhase" to "This was the final phase of the project. 🎉",
            "mailAction" to "Action: open the 1828 Tracker → Approvals to review.",
            "mailBy" to "By",
            "mailWhen" to "Time",
            "lblContext" to "Regarding",
            "lblProject" to "Project",
            "lblPhase" to "Phase",
            // Google Drive attachments
            "addDocument" to "+ 📎 Document",
            "attachDialogTitle" to "Attach document",
            "attachUrlLabel" to "Google Drive link or URL",
            "attachNameLabel" to "Name (optional)",
            "attachInvalidUrl" to "Invalid link.",
            "reviewDocs" to "Documents for review",
            "mailDocs" to "Documents",
            "kindFolder" to "Drive folder",
            "kindFile" to "Drive file",
            "kindLink" to "Link",
            // Password reset / change
            "forgotPassword" to "Forgot password?",
            "resetTitle" to "Reset password",
            "resetSub" to "Enter your email address; you'll receive a code by email.",
            "btnSendCode" to "Send code",
            "resetCodeSent" to "Code sent. Check your email (in this demo: the outbox folder).",
            "labelCode" to "Code from the email",
            "labelNewPassword" to "New password",
            "labelConfirmPassword" to "Confirm password",
            "btnResetPassword" to "Set password",
            "resetSuccess" to "Password updated. Sign in with your new password.",
            "resetFailBadCode" to "Wrong or expired code.",
            "pwMismatch" to "Passwords do not match.",
            "changePwTitle" to "Change password",
            "labelCurrentPassword" to "Current password",
            "changePwSuccess" to "Password changed.",
            "changePwFailCurrent" to "Current password incorrect.",
            "subjReset" to "🔑 Password reset code",
            "mailResetIntro" to "Use this code to reset your password:",
            "mailResetIgnore" to "Didn't request a reset? Ignore this email.",
            "evReset" to "Password reset",
            // Remove user
            "btnRemoveUser" to "Remove",
            "removeUserTitle" to "Remove user",
            "removeUserPrompt" to "Choose who takes over {user}'s documents and responsibilities:",
            "removeUserConfirmBtn" to "Remove and hand over",
            "removedInfo" to "{user} removed. {n} document(s) handed over to {to}.",
            "cannotRemoveOwner" to "The owner cannot be removed.",
            // Unfinished tasks on submit
            "notReadyBanner" to "{n} tasks still open in this phase.",
            "btnProceed" to "Proceed",
            "unfinishedPrompt" to "There are unfinished tasks ({n}) — do you want to proceed with submitting?",
            "unfinishedChoice" to "What should happen to the {n} open tasks?",
            "optMarkNa" to "Mark as not applicable",
            "optMoveNext" to "Move to next phase (WIP)",
            // City gate (municipality development before acquisition)
            "lblCity" to "City",
            "cityApprovedTitle" to "Municipality development approved",
            "cityApprovedDesc" to "Projects in this city are unlocked.",
            "cityLockedMsg" to "Municipality development for {city} must be approved first.",
            "cityGateHint" to "Projects unlock once municipality development is approved.",
            "subjCityApproval" to "📥 Approval requested: Municipality development — {city}",
            "subjCityApproved" to "🎉 Municipality development approved — {city}",
            "subjCityRejected" to "↩ Submission rejected: Municipality development — {city}",
            "mailCityApprovalIntro" to "{user} requests approval for municipality development.",
            "mailCityApprovedIntro" to "{user} approved municipality development. Projects in the city are unlocked.",
            "mailCityRejectedIntro" to "{user} rejected the submission. Review the tasks and resubmit.",
            // Zoom
            "zoomTooltip" to "Text size — click the percentage to reset",
        ),
    )

    fun t(key: String): String = tables[lang]?.get(key) ?: tables[Lang.NL]?.get(key) ?: key
}
